payapp/urls.py
from django.urls import path

from .views import (
    HomeTemplateView, TransactionListView, TransactionCreateView,
    TransactionRequestListView, TransactionRequestCreateView, TransactionRequestUpdateView,
    CurrencyConversionAPI, DashboardTemplateView

)


app_name = 'payapp'
urlpatterns = [

    # WEBSITE HOME PAGE
    path('', HomeTemplateView.as_view(), name='dashboard'),

    # USER DASHBOARD
    path('dashboard/', DashboardTemplateView.as_view(), name='dashboard'),

    # TRANSACTIONS SERVICES
    path('transaction/', TransactionListView.as_view(), name='transactions'),
    path('transaction/create/', TransactionCreateView.as_view(), name='transaction-create'),

    # REQUESTS SERVICES
    path('request/', TransactionRequestListView.as_view(), name='requests'),
    path('request/create/', TransactionRequestCreateView.as_view(), name='request-create'),
    path('request/<int:pk>/update/', TransactionRequestUpdateView.as_view(), name='request-update'),

    # API FOR CURRENCY CONVERSION
    path(
        'conversion/<str:currency1>/<str:currency2>/<str:amount>/',
        CurrencyConversionAPI.as_view(), name='currency-conversion-api'
    )

]

register/urls.py
from register.views import register_request, cross_auth
from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'register'

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(template_name='register/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),
    path('signup/', register_request, name='signup'),
    path('cross-auth/', cross_auth, name='cross-auth')

]

webapps2023/urls.py
from django.contrib import admin
from django.urls import path, include

from webapps2023.settings import ENVIRONMENT

urlpatterns = [
    path('admin/', admin.site.urls),
]

# your apps urls
urlpatterns += [
    path('', include('register.urls', namespace='register')),
    path('', include('payapp.urls', namespace='payapp')),
]

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

payapp/models.py
from django.db import models

from payapp.utils import convert_currency
from register.models import User


class Transaction(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_from')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_by')
    amount = models.FloatField()

    is_completed = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Transferred {self.amount} from {self.sender.get_full_name()} to {self.receiver.get_full_name()}"

    def save(self, *args, **kwargs):
        # self.amount = convert_currency(self.sender.currency_type, self.receiver.currency_type, self.amount)
        return super(Transaction, self).save(*args, **kwargs)


class TransactionRequest(models.Model):
    STATUS_CHOICE = (
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('cancelled', 'Cancelled'),
    )
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='request_from')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='request_to')
    amount = models.FloatField()

    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='pending')
    created_on = models.DateTimeField(auto_now_add=True)
    checked_on = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Transactions Requests'
        ordering = ['-created_on']

    def __str__(self):
        return f"Transferred {self.amount} from {self.sender.get_full_name()} to {self.receiver.get_full_name()}"

payapp/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from rest_framework.response import Response

from django.views.generic import ListView, DetailView, TemplateView

from payapp.models import Transaction, TransactionRequest
from payapp.utils import convert_currency, convert_to_float
from register.models import User
from rest_framework.views import APIView
from rest_framework.status import (
    HTTP_200_OK, HTTP_400_BAD_REQUEST
)
from register.models import User


class HomeTemplateView(TemplateView):
    template_name = 'payapp/home.html'


@method_decorator(login_required, name='dispatch')
class DashboardTemplateView(TemplateView):
    template_name = 'payapp/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardTemplateView, self).get_context_data(**kwargs)
        transactions = Transaction.objects.filter(Q(sender=self.request.user) | Q(receiver=self.request.user))
        requests = TransactionRequest.objects.filter(Q(sender=self.request.user) | Q(receiver=self.request.user))
        context['recent_transactions'] = transactions[0:10]
        context['recent_requests'] = requests[0:10]
        context['total_transactions'] = transactions.count()
        context['total_amount'] = User.objects.get(id=self.request.user.id)
        return context


""" TRANSACTION VIEWS"""


@method_decorator(login_required, name='dispatch')
class TransactionListView(ListView):
    template_name = 'payapp/transactions.html'
    context_object_name = 'objects'

    def get_queryset(self):
        return Transaction.objects.filter(
            Q(sender=self.request.user) | Q(receiver=self.request.user)
        )


@method_decorator(login_required, name='dispatch')
class TransactionDetailView(DetailView):

    def get_object(self, queryset=None):
        return get_object_or_404(
            Transaction.objects.filter(Q(sender=self.request.user) | Q(receiver=self.request.user)),
            pk=self.kwargs['pk']
        )


@method_decorator(login_required, name='dispatch')
class TransactionCreateView(View):
    template_name = 'payapp/transaction_create.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        email = request.POST.get('email')
        amount = request.POST.get('amount')

        # IF: missing parameters
        if not email or not amount:
            messages.warning(request, "Email or Amount is missing")
            return redirect('payapp:transaction-create')

        receiver = User.objects.filter(email=email)

        # IF: no receiver
        if not receiver:
            messages.error(request, "User doesn't exists with this email address")
            return redirect('payapp:transaction-create')

        sender = request.user
        receiver = receiver[0]

        # IF: same user
        if receiver == sender:
            messages.warning(request, "You can't sent amounts to yourself")
            return redirect('payapp:transaction-create')

        # IF: amount issue
        if sender.total_amount <= float(amount):
            messages.warning(request, "In sufficient balance to perform this transaction")
            return redirect('payapp:transaction-create')

        # ADD: transaction
        Transaction.objects.create(sender=sender, receiver=receiver, amount=amount)
        receiver.total_amount += float(amount)
        receiver.save()
        sender.total_amount -= float(amount)
        sender.save()
        messages.success(request, "Amount Transferred successfully.")
        return redirect('payapp:transactions')


""" TRANSACTION REQUEST VIEWS"""


@method_decorator(login_required, name='dispatch')
class TransactionRequestListView(ListView):
    template_name = 'payapp/request_transaction_list.html'

    def get_queryset(self):
        return TransactionRequest.objects.filter(
            Q(sender=self.request.user) | Q(receiver=self.request.user)
        )


@method_decorator(login_required, name='dispatch')
class TransactionRequestDetailView(DetailView):

    def get_object(self, queryset=None):
        return get_object_or_404(
            TransactionRequest.objects.filter(Q(sender=self.request.user) | Q(receiver=self.request.user)),
            pk=self.kwargs['pk']
        )


@method_decorator(login_required, name='dispatch')
class TransactionRequestCreateView(View):
    template_name = 'payapp/request_transaction_create.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        email = request.POST.get('email')
        amount = request.POST.get('amount')

        # IF: no status parameter
        if not email or not amount:
            messages.warning(request, "Email or Amount is missing")
            return redirect('payapp:request-create')

        # IF: receiver not available
        request_from = User.objects.filter(email=email)
        if not request_from:
            messages.error(request, "User doesn't exists with this email address")
            return redirect('payapp:request-create')

        request_to = request.user
        request_from = request_from[0]

        # IF: same user
        if request_from == request_to:
            messages.warning(request, "You can't request amounts from yourself")
            return redirect('payapp:request-create')

        # SUCCESS: create transaction
        TransactionRequest.objects.create(sender=request_to, receiver=request_from, amount=amount)
        messages.success(request, "Your transactions request added successfully")
        return redirect('payapp:requests')


@method_decorator(login_required, name='dispatch')
class TransactionRequestUpdateView(View):

    def get(self, request, pk):

        # IF: no status parameter
        status = request.GET.get('status')

        # IF: get transaction or 404
        transaction_request = get_object_or_404(
            TransactionRequest.objects.filter(receiver=request.user, status='pending'), pk=pk
        )
        sender = transaction_request.receiver
        receiver = transaction_request.sender
        amount = transaction_request.amount

        # IF: wrong parameter
        if status not in ['approved', 'cancel']:
            messages.warning(request, "Some parameters are missing")
            return redirect('payapp:requests')

        if status == "cancel":
            transaction_request.status = "cancelled"
            transaction_request.checked_on = datetime.datetime.now()
            transaction_request.save()
            return redirect('payapp:requests')

        # IF: sender amount is less
        if amount > sender.total_amount:
            messages.warning(request, "In sufficient balance to perform this transaction")
            return redirect('payapp:requests', )

        # ADD: transaction
        Transaction.objects.create(
            sender=sender, receiver=receiver, amount=amount
        )

        # ADD: transaction
        Transaction.objects.create(
            sender=sender, receiver=receiver, amount=amount
        )

        # UPDATE: sender and receiver amounts
        sender.total_amount -= amount
        sender.save()
        receiver.total_amount += amount
        receiver.save()

        transaction_request.status = 'accepted'
        messages.success(request, "Request approved and transaction performed successfully")

        # UPDATE: request
        transaction_request.checked_on = datetime.datetime.now()
        transaction_request.save()

        # SUCCESS: message and redirect

        return redirect('payapp:requests')


""" API """


@method_decorator(login_required, name='dispatch')
class CurrencyConversionAPI(APIView):
    def get(self, request, currency1, currency2, amount):

        # IF: currencies not supported
        if currency1 not in ['USD', 'EURO', 'GBP'] or currency2 not in ['USD', 'EURO', 'GBP']:
            return Response(
                status=HTTP_400_BAD_REQUEST, data={
                    'error': 'Only USD, EURO and GBP are supported'
                }
            )

        float_amount = convert_to_float(amount)

        # IF: not supported to convert into int or float
        if not float_amount:
            return Response(
                status=HTTP_400_BAD_REQUEST, data={
                    'error': 'Amount must be number (integer, float)'
                }
            )

        # IF: amount is less or equal to 0
        if float_amount <= 0:
            return Response(
                status=HTTP_200_OK, data={
                    'error': 'Amount must be numeric and greater than 0'
                }
            )

        # SUCCESS: everything is fine here
        converted_amount = convert_currency(currency1, currency2, float_amount)
        return Response(
            status=HTTP_200_OK, data={
                'amount': converted_amount
            }
        )

templates/payapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">
<link href="images/favicon.png" rel="icon" />
<title>Online Payment Service</title>
<meta name="description" content="This professional design html template is for build a Money Transfer and online payments website.">
<meta name="author" content="harnishdesign.net">

<!-- Web Fonts
============================================= -->

<!-- Stylesheet
============================================= -->
<link rel="stylesheet" type="text/css" href="{% static 'website/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'website/css/all.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'website/css/owl.carousel.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'website/css/stylesheet.css' %}" />
<!-- Colors Css -->
<link id="color-switcher" type="text/css" rel="stylesheet" href="#" />
</head>
<body>

{% block content %}

{% endblock content %}
<script src="{% static 'website/js/jquery.min.js' %}"></script>
<script src="{% static 'website/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'website/js/owl.carousel.min.js' %}"></script>
<!-- Style Switcher -->
<script src="{% static 'website/js/switcher.min.js' %}"></script>
<script src="{% static 'website/js/theme.js' %}"></script>
</body>
</html>

templates/payapp/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
    Dashboard
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-4">
                    <div class="d-flex">
                        <div class="flex-shrink-0 me-3">
                            <img alt="" class="avatar-md rounded-circle img-thumbnail"
                                 src="{% static 'admin/images/base/no-user.png' %}">
                        </div>
                        <div class="flex-grow-1 align-self-center">
                            <div class="text-muted">
                                <p class="mb-2">Welcome to Dashboard</p>
                                <h5 class="mb-1">{{ request.user.get_name_info }}</h5>
                                <p class="mb-0">{{ request.user.email }}</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-8 align-self-center">
                    <div class="text-lg-center mt-4 mt-lg-0">
                        <div class="row">
                            <div class="col">
                                <div>
                                    <p class="text-muted text-truncate mb-2">Amount</p>
                                    <h5 class="mb-0">{{ request.user.total_amount }}</h5>
                                </div>
                            </div>
                            <div class="col">
                                <div>
                                    <p class="text-muted text-truncate mb-2">Currency</p>
                                    <h5 class="mb-0">{{ request.user.currency_type }}</h5>
                                </div>
                            </div>
                            <div class="col">
                                <div>
                                    <p class="text-muted text-truncate mb-2">Send Amount</p>
                                    <h5 class="mb-0">{{ request.user.sent_amount }}</h5>
                                </div>
                            </div>
                            <div class="col">
                                <div>
                                    <p class="text-muted text-truncate mb-2">Transactions</p>
                                    <h5 class="mb-0">{{ total_transactions }}</h5>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end row -->
        </div>
    </div>

    <div class="card">
        <div class="card-body border-bottom">
            <div class="row">
                <div class="col-6">
                    <p class="mb-0 h4">
                        <i class="bx bx-transfer"></i> Recent Transactions
                    </p>
                </div>
                <div class="col-6 text-right">
                    <p class="mb-0">
                        <a href="{% url 'payapp:transactions' %}">
                            <b>View More</b>
                        </a>
                    </p>
                </div>
            </div>
        </div>
        {% if recent_transactions %}
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table align-middle table-nowrap table-check">
                        <thead class="table-light">
                        <tr>
                            <th class="align-middle">ID</th>
                            <th class="align-middle">Sender</th>
                            <th class="align-middle">Receiver</th>
                            <th class="align-middle">Amount</th>
                            <th class="align-middle">Type</th>
                            <th class="align-middle">Status</th>
                            <th class="align-middle">Created</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for objects in recent_transactions %}
                            <tr>
                                <td>
                                    <b># {{ objects.id }}</b>
                                </td>
                                <td>
                                    {% if objects.sender == request.user %}
                                        <b>You</b>
                                    {% else %}
                                        {{ objects.sender.get_name_info }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if objects.receiver == request.user %}
                                        <b>You</b>
                                    {% else %}
                                        {{ objects.receiver.get_name_info }}
                                    {% endif %}
                                </td>
                                <td>
                                    <b>{{ objects.amount }} {{ request.user.currency_type }}</b>
                                </td>
                                <td>
                                    <b>
                                        {% if objects.sender == request.user %}
                                            <i class="fa fa-arrow-up text-primary"></i> Send
                                        {% else %}
                                            <i class="fa fa-arrow-down text-primary"></i> Received
                                        {% endif %}
                                    </b>
                                </td>
                                <td>
                                    <b>
                                        {% if objects.is_completed %}
                                            <i class="fa fa-check-circle text-success"></i> completed
                                        {% else %}
                                            <i class="fa fa-times-circle text-danger"></i> cancelled
                                        {% endif %}
                                    </b>
                                </td>
                                <td>
                                    <i class="fab me-1"></i> {{ objects.created_on }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="card-body">
                <p class="mb-0 text-danger">
                    <b>No transactions available</b>
                </p>
            </div>
        {% endif %}
    </div>

    <div class="card">
        <div class="card-body border-bottom">
            <div class="row">
                <div class="col-6">
                    <p class="mb-0 h4">
                        <i class="bx bx-transfer"></i> Recent Requests
                    </p>
                </div>
                <div class="col-6 text-right">
                    <p class="mb-0">
                        <a href="{% url 'payapp:requests' %}">
                            <b>View More</b>
                        </a>
                    </p>
                </div>
            </div>
        </div>
        {% if recent_requests %}
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table align-middle table-nowrap table-check">
                        <thead class="table-light">
                        <tr>
                            <th class="align-middle">ID</th>
                            <th class="align-middle">Sender</th>
                            <th class="align-middle">Receiver</th>
                            <th class="align-middle">Amount</th>
                            <th class="align-middle">Type</th>
                            <th class="align-middle">Status</th>
                            <th class="align-middle">Created</th>
                            <th class="align-middle">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for objects in recent_requests %}
                            <tr>
                                <td>
                                    <b># {{ objects.id }}</b>
                                </td>
                                <td>
                                    {% if objects.sender == request.user %}
                                        <b>You</b>
                                    {% else %}
                                        {{ objects.sender.get_name_info }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if objects.receiver == request.user %}
                                        <b>You</b>
                                    {% else %}
                                        {{ objects.receiver.get_name_info }}
                                    {% endif %}
                                </td>
                                <td>
                                    <b>{{ objects.amount }} {{ request.user.currency_type }}</b>
                                </td>
                                <td>
                                    <b>
                                        {% if objects.sender == request.user %}
                                            <i class="fa fa-arrow-up text-primary"></i> Send
                                        {% else %}
                                            <i class="fa fa-arrow-down text-primary"></i> Received
                                        {% endif %}
                                    </b>
                                </td>
                                <td>
                                    <b>
                                        {% if objects.status == 'pending' %}
                                            <i class="fa fa-clock text-warning"></i> {{ objects.get_status_display }}
                                        {% elif objects.status == 'accepted' %}
                                            <i class="fa fa-check-circle text-success"></i>
                                            {{ objects.get_status_display }}
                                        {% else %}
                                            <i class="fa fa-times-circle text-danger"></i>
                                            {{ objects.get_status_display }}
                                        {% endif %}
                                    </b>
                                </td>
                                <td>
                                    <i class="fab me-1"></i> {{ objects.created_on }}
                                </td>
                                                    <td>
                        {% if objects.receiver == request.user %}
                        {% if objects.status == "pending" %}
                        <a href="{% url 'payapp:request-update' objects.id %}?status=approved"><span
                                class="badge badge-pill badge-soft-success font-size-12">Accept</span></a>
                        <a href="{% url 'payapp:request-update' objects.id %}?status=cancel"><span
                                class="badge badge-pill badge-soft-danger font-size-12">Cancel</span></a>
                        {% elif objects.status == "approved" %}
                        <a href="#"><span
                                class="badge badge-pill badge-soft-success font-size-12">{{objects.status}}</span></a>
                        {% else %}
                        <a href="#"><span
                                class="badge badge-pill badge-soft-secondary font-size-12">{{objects.status}}</span></a>
                        {% endif %}
                        {% elif objects.sender == request.user %}
                        {% if objects.status == "pending" %}
                        <span
                                class="badge badge-pill badge-soft-primary font-size-12">{{objects.status}}</span>
                        {% elif objects.status == "approved" %}
                        <span
                                class="badge badge-pill badge-soft-success font-size-12">{{objects.status}}</span>
                        {% else %}
                        <span
                                class="badge badge-pill badge-soft-secondary font-size-12">{{objects.status}}</span>
                        {% endif %}
                        {% endif %}

                    </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="card-body">
                <p class="mb-0 text-danger">
                    <b>No requests available</b>
                </p>
            </div>
        {% endif %}
    </div>


{% endblock content %}

templates/payapp/home.html
{% extends 'payapp/base.html' %}
{% load static %}
{% block content %}
<!-- Preloader -->
<div id="preloader">
  <div data-loader="dual-ring"></div>
</div>
<!-- Preloader End -->

<!-- Document Wrapper
============================================= -->
<div id="main-wrapper">

  <!-- Header
  ============================================= -->
  <header id="header">
    <div class="container">
      <div class="header-row">
        <div class="header-column justify-content-start">
          <!-- Logo
          ============================= -->
          <div class="logo me-3"> <a class="d-flex" href="index.html" title="Payyed - HTML Template">
              <img src="{% static 'logo.png' %}" width="100" height="auto"  alt="Payment Service" /></a>
          </div>
          <!-- Logo end -->
          <!-- Collapse Button
          ============================== -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#header-nav"> <span></span> <span></span> <span></span> </button>
          <!-- Collapse Button end -->

          <!-- Primary Navigation
          ============================== -->
          <!-- Primary Navigation end -->
        </div>
        <div class="header-column justify-content-end">
          <!-- Login & Signup Link
          ============================== -->
          <nav class="login-signup navbar navbar-expand">
            <ul class="navbar-nav">
              <li><a href="{% url 'register:login' %}">Login</a> </li>
              <li class="align-items-center h-auto ms-sm-3"><a class="btn btn-primary" href="{% url 'register:signup' %}">Sign Up</a></li>
            </ul>
          </nav>
          <!-- Login & Signup Link end -->
        </div>
      </div>
    </div>
  </header>
  <!-- Header End -->

  <!-- Content
  ============================================= -->
  <div id="content">

    <!-- Slideshow
    ============================================= -->
	<div class="owl-carousel owl-theme single-slideshow" data-autoplay="true" data-loop="true" data-autoheight="true" data-nav="true" data-items="1">
      <div class="item">
        <section class="hero-wrap">
          <div class="hero-mask opacity-7 bg-dark"></div>
          <div class="hero-bg" style="background-image:url('{% static 'website/images/image-1.jpg' %}');"></div>
          <div class="hero-content d-flex fullscreen-with-header py-5">
            <div class="container my-auto text-center">
              <h2 class="text-16 text-white">Send & Receive Money</h2>
              <p class="text-5 text-white mb-4">Quickly and easily send, receive and request money online with Payyed.<br class="d-none d-lg-block">
                Over 180 countries and 4 currencies supported.</p>
              <a href="{% url 'register:signup' %}" class="btn btn-primary m-2">Open a Free Account</a> </div>
          </div>
        </section>
      </div>
      <div class="item">
        <section class="hero-wrap">
          <div class="hero-bg" style="background-image:url('{% static 'website/images/image-3.jpg' %}');"></div>
          <div class="hero-content d-flex fullscreen-with-header py-5">
            <div class="container my-auto">
              <div class="row">
                <div class="col-12 col-lg-8 col-xl-7 text-center text-lg-start">
                  <h2 class="text-13 text-white">Trusted by more than 50,000 businesses worldwide.</h2>
                  <p class="text-5 text-white mb-4">Over 180 countries and 4 currencies supported.</p>
                  <a href="{% url 'register:signup' %}" class="btn btn-primary me-3">Get started for free</a> </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
    <!-- Slideshow end -->


    <!-- Mobile App end -->

  </div>
  <!-- Content end -->


</div>
<!-- Document Wrapper end -->

{% endblock content%}