payapp/urls.py
from django.urls import path

from .views import (
    HomeTemplateView, TransactionListView, TransactionCreateView,
    TransactionRequestListView, TransactionRequestCreateView, TransactionRequestUpdateView,
    CurrencyConversionAPI, DashboardTemplateView

)


app_name = 'payapp'
urlpatterns = [

    # WEBSITE HOME PAGE
    path('', HomeTemplateView.as_view(), name='dashboard'),

    # USER DASHBOARD
    path('dashboard/', DashboardTemplateView.as_view(), name='dashboard'),

    # TRANSACTIONS SERVICES
    path('transaction/', TransactionListView.as_view(), name='transactions'),
    path('transaction/create/', TransactionCreateView.as_view(), name='transaction-create'),

    # REQUESTS SERVICES
    path('request/', TransactionRequestListView.as_view(), name='requests'),
    path('request/create/', TransactionRequestCreateView.as_view(), name='request-create'),
    path('request/<int:pk>/update/', TransactionRequestUpdateView.as_view(), name='request-update'),

    # API FOR CURRENCY CONVERSION
    path(
        'conversion/<str:currency1>/<str:currency2>/<str:amount>/',
        CurrencyConversionAPI.as_view(), name='currency-conversion-api'
    )

]

register/urls.py
from register.views import register_request, cross_auth
from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'register'

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(template_name='register/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),
    path('signup/', register_request, name='signup'),
    path('cross-auth/', cross_auth, name='cross-auth')

]

webapps2023/urls.py
from django.contrib import admin
from django.urls import path, include

from webapps2023.settings import ENVIRONMENT

urlpatterns = [
    path('admin/', admin.site.urls),
]

# your apps urls
urlpatterns += [
    path('', include('register.urls', namespace='register')),
    path('', include('payapp.urls', namespace='payapp')),
]

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

templates/base.html
{% load static %}
{#{% load notifications_tags %}#}

<!doctype html>
<html lang="en">
<head>
    <link rel="icon" href="{% static 'logo.png' %}">
    <title>

        {% block title %}
            Webapps2023 |

            {# BASE HALF TITLE #}
            {% block subtitle %}

            {% endblock %}
            {# --------------- #}
        {% endblock %}

    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'admin/css/app.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'admin/css/icons.min.css' %}">


    {# BASE LINKS THAT ARE REQUIRED FOR CERTAIN PAGE #}
    {% block css %}

    {% endblock %}
    {# --------------------------------------------- #}

</head>
<body data-topbar="dark" data-layout="horizontal">

{% block only-body %}

    <!-- Begin page -->
    <div id="layout-wrapper">

        {# BASE TOP NAVIGATION PANEL AREA #}
        {% block base_top_nav %}
            {% include 'navbar.html' %}
        {% endblock %}
        {# ------------------------------ #}


        {% block dont_include_details %}

            <div class="main-content">

                <div class="page-content mt-4">
                    <div class="container-fluid mt-5">
                        <div class="row">
                           {% include 'messages.html' %}
                        </div>

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0 font-size-18">

                                        {% block page_heading %} {% endblock %}</h4>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->

                        <div class="row">
                            <div class="col-12">
                                {% block content %}

                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        {% endblock %}
    </div>

{#    <div class="right-bar">#}
{#        <div data-simplebar="init" class="h-100">#}
{#            <div class="simplebar-wrapper" style="margin: 0px;">#}
{#                <div class="simplebar-height-auto-observer-wrapper">#}
{#                    <div class="simplebar-height-auto-observer"></div>#}
{#                </div>#}
{#                <div class="simplebar-mask">#}
{#                    <div class="simplebar-offset" style="right: 0px; bottom: 0px;">#}
{#                        <div class="simplebar-content-wrapper" style="height: 100%; overflow: hidden;">#}
{#                            <div class="simplebar-content" style="padding: 0px;">#}
{#                                <div class="rightbar-title px-3 py-4">#}
{#                                    <a href="javascript:void(0);" class="right-bar-toggle float-right">#}
{#                                        <i class="mdi mdi-close noti-icon"></i>#}
{#                                    </a>#}
{#                                    <h5 class="m-0">Settings</h5>#}
{#                                </div>#}
{##}
{#                                <!-- Settings -->#}
{#                                <hr class="mt-0">#}
{#                                <h6 class="text-center mb-0">Choose Layouts</h6>#}
{##}
{#                                <div class="p-4">#}
{#                                    <div class="mb-2">#}
{#                                        <img src="{% static 'exarth/images/layouts/layout-1.jpg" class="img-fluid img-thumbnail"#}
{#                                             alt="">#}
{#                                    </div>#}
{#                                    <div class="custom-control custom-switch mb-3">#}
{#                                        <input type="checkbox" class="custom-control-input theme-choice"#}
{#                                               id="light-mode-switch" checked="">#}
{#                                        <label class="custom-control-label" for="light-mode-switch">Light Mode</label>#}
{#                                    </div>#}
{##}
{#                                    <div class="mb-2">#}
{#                                        <img src="{% static 'exarth/images/layouts/layout-2.jpg" class="img-fluid img-thumbnail"#}
{#                                             alt="">#}
{#                                    </div>#}
{#                                    <div class="custom-control custom-switch mb-3">#}
{#                                        <input type="checkbox" class="custom-control-input theme-choice"#}
{#                                               id="dark-mode-switch" data-bsstyle="assets/css/bootstrap-dark.min.css' %}"#}
{#                                               data-appstyle="assets/css/app-dark.min.css' %}">#}
{#                                        <label class="custom-control-label" for="dark-mode-switch">Dark Mode</label>#}
{#                                    </div>#}
{##}
{#                                    <div class="mb-2">#}
{#                                        <img src="{% static 'exarth/images/layouts/layout-3.jpg" class="img-fluid img-thumbnail"#}
{#                                             alt="">#}
{#                                    </div>#}
{#                                    <div class="custom-control custom-switch mb-5">#}
{#                                        <input type="checkbox" class="custom-control-input theme-choice"#}
{#                                               id="rtl-mode-switch" data-appstyle="assets/css/app-rtl.min.css' %}">#}
{#                                        <label class="custom-control-label" for="rtl-mode-switch">RTL Mode</label>#}
{#                                    </div>#}
{##}
{##}
{#                                </div>#}
{##}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="simplebar-placeholder" style="width: auto; height: 839px;"></div>#}
{#            </div>#}
{#            <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">#}
{#                <div class="simplebar-scrollbar" style="transform: translate3d(0px, 0px, 0px); display: none;"></div>#}
{#            </div>#}
{#            <div class="simplebar-track simplebar-vertical" style="visibility: hidden;">#}
{#                <div class="simplebar-scrollbar" style="transform: translate3d(0px, 0px, 0px); display: none;"></div>#}
{#            </div>#}
{#        </div> <!-- end slimscroll-menu-->#}
{#    </div>#}

    <div class="rightbar-overlay"></div>
{#     jQuery first, then Popper.js, then Bootstrap JS#}
{#    <script src="{% static 'core/helper.js' %}"></script>#}

    <script src="{% static 'admin/libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'admin/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'admin/libs/metismenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'admin/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static 'admin/libs/node-waves/waves.min.js' %}"></script>
    {#<script src="{% static 'core/moment.js' %}"></script>#}

    <!-- App js -->
    <script src="{% static 'admin/js/app.js' %}"></script>

    {#    <script src="{% static 'core/js/notify.js' %}" type="text/javascript"></script>#}
    {#    {% register_notify_callbacks callbacks='fill_notification_badge,my_special_notification_callback' %}#}


    {# BASE INTERNAL SCRIPTS OR LINKS THAT ARE REQUIRED IN PAGE #}
    {% block js %}

    {% endblock %}
    {# -------------------------------------------------------- #}

{% endblock %}

</body>
</html>


{# BASE EXTERNAL SCRIPTS OR LINKS THAT ARE REQUIRED IN PAGE #}
{% block js_code %}

{% endblock %}
{# -------------------------------------------------------- #}

templates/messages.html
<div>
    {% if messages %}
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'debug' %}
                <div class="alert alert-dark alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
</div>

templates/navbar.html
{% load static %}
{#{% load notifications_tags %}#}

<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="/" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src="{% static 'logo.png' %}" alt="" height="35">
                                </span>
                    <span class="logo-lg">
                                    <img src="{% static 'logo.png' %}" alt="" height="35">
                                </span>
                </a>

                <a href="/" class="logo logo-light">
                                <span class="logo-sm">
                                    <img src="{% static 'logo.png' %}" alt="" height="35">
                                </span>
                    <span class="logo-lg">
                                    <img src="{% static 'logo.png' %}" alt="" height="35">
                                </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                    data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

        </div>

        <div class="d-flex">

            {# FULL_SCREEN #}
            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            {# NOTIFICATIONS #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                        id="page-header-notifications-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge badge-danger badge-pill">
{#                        {% live_notify_badge %}#}
                    </span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                     aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#" class="small"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 420px;">
                        <div id="notify_me_now">

                        </div>
                        <div class="p-2 border-top text-center">
                            <button class="btn text-primary small" onclick="unread_all_notifications()">
                                <i class="mdi mdi-arrow-right-circle mr-1"></i> Mark All as Read
                            </button>
                        </div>
                    </div>
                </div>

            </div>

            {# USER ONLINE #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user"

                         src="{% static 'admin/images/base/no-user.png' %}"
                         alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ml-1">{{ request.user.username }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item text-primary" href="{% url 'register:logout' %}">
                        <i class="bx bx-power-off font-size-16 align-middle mr-1"></i> Logout
                    </a>
                </div>
            </div>

        </div>
    </div>
</header>


<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'payapp:dashboard' %}">
                            <i class="bx bx-home-circle mr-2"></i>Dashboard
                        </a>
                    </li>
                        <li class="nav-item">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'payapp:transactions' %}">
                            <i class="bx bx-user mr-2"></i>Send Transactions
                        </a>
                    </li>
                        <li class="nav-item">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'payapp:requests' %}">
                            <i class="bx bx-user mr-2"></i>Request Transactions
                        </a>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>